# Generated by Django 5.2.1 on 2025-06-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logatividade',
            name='user_agent',
            field=models.TextField(blank=True, help_text='Informações do navegador/dispositivo', null=True),
        ),
    ]
