# Generated by Django 5.2.1 on 2025-06-03 21:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_logatividade_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, help_text='Telefone no formato +245XXXXXXX', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Formato de telefone inválido. Use +245XXXXXXX ou XXXXXXX', regex='^(\\+245)?9[0-9]{8}$')]),
        ),
    ]
